### PR TITLE
Update gripmock for new protogen, opentelemetry tracing, cleanups

### PR DESCRIPTION
**Pull request by ringerc**
Instrument gRPC requests with OpenTelemetry trace support.

The following exporters are supported by default:

* OpenTelemetry collector (gRPC and HTTP) https://opentelemetry.io/docs/reference/specification/sdk-environment-variables/#otlp-exporter
* Zipkin https://opentelemetry.io/docs/reference/specification/sdk-environment-variables/#zipkin-exporter
* Stdout

While metrics exporter support is not introduced by this commit, it would be trivial to add metrics for gRPC request processing etc using the same OpenTelemetry API.

The instrumentation provided does not capture request headers and payloads or response headers and payloads. Another gRPC interceptor could be used to optionally record this information.

The stubs API server is not instrumented, as it is not considered interesting for application tracing.

Detailed usage is in the patch to the `Readme.md` 

# Comments requested

Supporting OpenTelemetry required some changes in how the server is built. Instead of a bare "go run", the server must be built with "go mod init", "go mod tidy", "go mod download", and "go build".

I also found it necessary to modify `fix_gopackage.sh` to stop it from inserting a `/./` path-component when a relative path to the `.proto` file was used as an argument.

This PR can be considered a draft / RFC, as I am not confident the implementation will be satisfactory as it stands. It is fairly invasive. The OpenTelemetry instrumentation setup could be extracted into its own module, but the `server.go` will still need to be able to use modules outside the core golang SDK to use it. 

Advice on how to implement this in a way that's minimally invasive for existing users would be welcomed.

### CODE REVIEW

**Comment by ringerc** [comment]
I marked this as draft as I'm unsure if the current includes logic works correctly when building using a `go.mod` file. I think it was using the examples off github, rather than local files, and am testing with an alternate paths.

**Comment by ringerc** [comment]
Getting opentelemetry support in place landed up being an omnibus PR that changed how the stubs build and a lot of other things.

I think I know how to update the gripmock base to support otel without all the other changes now, by using "go mod download" to pre-install the various otel deps into the go `src` directory. I'll see about doing that.

Is this repo still alive though? It won't be worth splitting this PR up if this gripmock isn't maintained. I might just carry it in my fork in https://github.com/ringerc/gripmock instead.

**Comment by ringerc** [comment]
From what I can see in the other github issues and PRs this upstream is inactive.

I've made a lot of changes to gripmock in my fork at https://github.com/ringerc/gripmock  - including opentelemetry support, proto3 optional, many cleanups, support for overriding the server template and more

**Comment by jekiapp** [comment]
Hi @ringerc, thanks for opening a new PR. For what I see, this change is too drastic of a change on how gripmock works. Our vision for gripmock is that it can reliably run .proto files for all usecases. I agree with you if you want to add some big features, it will be wise to do it on your own fork. so that others can also fork and modify gripmock from a basic working framework. (even "basic" here is already quite complicated for most of us)

**Comment by ringerc** [comment]
@jekiapp I can work with that. I can probably factor out the opentelemetry support to work without the other changes - it just took me quite a while to understand the ideas behind how gripmock works using its legacy / pre-go-module server builds etc, so I went down the wrong path for that.

I'll close this though. If you're interested in otel trace event support ping me and I'll raise a separate and simpler PR.

**Comment by ringerc** [comment]
With that said, you'll probably need to adopt a bunch of my changes anyway - getting rid of the obsolete protogen invocation etc. Feel free to cherry-pick anything you want from the fork.

**Pull request closed without merging**
