### PR TITLE
use native json marshaling to map stubbed output

### PR DESCRIPTION
**Pull request by vincent-raman**
When an output field had a '_' in its name, it was not mapped
correctly by 'mapstructure' to the protoc generated class because,
in this class, the fields are translated in CamelCase.
Hower, the fields have json tag with their original name.
Json marshalling is then the way to fix this issue.

Fixes tokopedia/gripmock/#46

### CODE REVIEW

**Comment by jekiapp** [comment]
Thanks @vincent-raman for the PR. 
Could you please also make a testcase for it. A simple update for the current example testcase is okay, just to prove the issue is solved. Please check `/example` folder for the test cases.

**Comment by vincent-raman** [comment]
Hi, I modified the basic example, does it seem ok for you ?

**Comment by jekiapp** [comment]
LGTM! thanks

**Comment by bjaglin** [comment]
I ran into this today, as it introduced a regression for my stubs generated with https://github.com/scalapb/scalapb-json4s. What's surprising me is that [the canonical proto3 encoding defaults to `lowerCamelCase`](https://developers.google.com/protocol-buffers/docs/proto3#json), so the previous behavior seemed more correct than the one introduced in this PR?

**Pull request merged**
